name: Deployment

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Environment & Authenticate
        uses: actions/setup-node@v3
        with:
          node-version: 16
          ref: ${{ github.sha }}
          fetch-depth: "0"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user.
        run: |
          git config --global user.email "vitorpeixoto14@hotmail.com"
          git config --global user.name "vitor-peixoto"

      - name: publish
        run: npm publish
