name: Docs

on:
  push:
    branches:
      - master

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Environment & Authenticate
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update git
        run: |
          cd docs
          git pull origin master
          git add .
          git commit -m "Update wiki content"
          git push origin master
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
